#!/bin/sh
# ------------------------------
# Window Manager Config
# ------------------------------
# Colors
riverctl background-color 0x282a36
riverctl border-color-focused 0xbd93f9
riverctl border-color-unfocused 0x44475a

# Keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# Declare a passthrough mode
riverctl declare-mode passthrough

# Set default layout generator
riverctl default-layout rivertile

# ------------------------------
# Key Bindings
# ------------------------------
# Spawn a terminal
riverctl map normal Super+Shift Return spawn "alacritty"

# Spawn a launcher
riverctl map normal Super P spawn "killall tofi-drun; tofi-drun"

# Spawn a power manager
riverctl map normal Super+Shift Q spawn "power_control.sh"

# Screenshot the screen
riverctl map normal Super S spawn "grim - | swappy -f -"
riverctl map normal Super+Shift S spawn "grim -g \"\$(slurp)\" - | swappy -f -"

# Switch between tags
riverctl map normal Super Tab focus-previous-tags

# Close the focused view
riverctl map normal Super Q close

# Exit river
riverctl map normal Super+Shift E exit

# Switch focused view
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Swap focused view
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Switch focused output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Send focused output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Bump focused view to master
riverctl map normal Super Return zoom

# Change window ration
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Change the main count of rivertile
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Snap views
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Move views with cursor
riverctl map-pointer normal Super BTN_LEFT move-view

# Resize views with cursor
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Loop through 9 tags
for i in $(seq 1 9); do
   tags=$((1 << ($i - 1)))

   # Focus tag
   riverctl map normal Super $i set-focused-tags $tags

   # Tag focused view with another tag
   riverctl map normal Super+Shift $i set-view-tags $tags

   # Toggle focus of a tag
   riverctl map normal Super+Control $i toggle-focused-tags $tags

   # Toggle the tag of a focused view
   riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Toggle float
riverctl map normal Super Space toggle-float

# Toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Switch to passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Switch to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Set media key mappings at different modes
for mode in normal locked; do
   # Control pulse audio volume with amixer
   riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn 'amixer -qD pipewire sset Master 5%+'
   riverctl map -repeat $mode None XF86AudioLowerVolume  spawn 'amixer -qD pipewire sset Master 5%-'
   riverctl map $mode None XF86AudioMute                 spawn 'amixer -qD pipewire sset Master toggle'

   # Control MPRIS aware media players with playerctl
   riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
   riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
   riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
   riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

   # Control screen backlight brighness with light
   riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
   riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# ------------------------------
# Auto-start applications
# ------------------------------
yambar &                                         # Statusbar at the top
dunst &                                          # Notification daemon
blueman-applet &                                 # Bluetooth Manager
swaybg -i "$HOME/Pictures/Wallpapers/arch.png" & # Set wallpaper

# Enable wayland screen sharing
/usr/lib/xdg-desktop-portal -r &
/usr/lib/xdg-desktop-portal-wlr -r &

# Change GTK settings
gsettings set org.gnome.desktop.interface gtk-theme "Dracula" &
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark" &
gsettings set org.gnome.desktop.interface font-name "Inter 10" &
gsettings set org.gnome.desktop.wm.preferences theme "Dracula" &
gsettings set org.gnome.desktop.wm.preferences button-layout "" &

# Execute the tiling part of river
rivertile -view-padding 1 -outer-padding 5 &    # Enable tiling for riverwm
