alias vi '$EDITOR'
alias ls '/usr/bin/ls -lhAv --group-directories-first --color=auto'
alias mkdir '/usr/bin/mkdir -p'
alias rm '/usr/bin/trash-put'
alias purge '/usr/bin/rm -r'
alias cp '/usr/bin/cp -r'
alias hibernate '/usr/bin/systemctl hibernate'
alias tree '/usr/bin/tree -aCL 3 --gitignore --dirsfirst'
alias dotfiles '/usr/bin/git --git-dir=$HOME/.repos/dotfiles --work-tree=$HOME'
alias cbclr '/usr/bin/wl-copy -c; wl-copy -cp' # clear clipboard
alias vg '/usr/bin/valgrind --leak-check=full --show-reachable=no --keep-debuginfo=yes --track-origins=yes'
