alias vi '$EDITOR'
alias ls 'ls -lhAv --group-directories-first --color=auto'
alias mkdir 'mkdir -p'
alias rm 'trash-put'
alias purge 'rm -r'
alias cp 'cp -r'
alias hibernate 'systemctl hibernate'
alias tree 'tree -aCL 3 --gitignore --dirsfirst'
alias dotfiles 'git --git-dir=$HOME/.repos/dotfiles --work-tree=$HOME'
alias cbclr 'wl-copy -c; wl-copy -cp' # clear clipboard
alias vg 'valgrind --leak-check=full --show-leak-kinds=all --keep-debuginfo=yes --track-origins=yes'
